import random

SAYINGS = (	
	'生活是一面鏡子。你對它笑，它就對你笑；你對它哭，它也對你哭。', 
	'活著一天，就是有福氣，就該珍惜。當我哭泣我沒有鞋子穿的時候，我發現有人卻沒有腳。', 
	'人生是個圓，有的人走了一輩子也沒有走出命運畫出的圓圈，其實，圓上的每一個點都有一條騰飛的切線。',
	'千萬別迷戀網絡遊戲，要玩就玩好人生這場大遊戲。',
	'命運負責洗牌，但是玩牌的是我們自己！',
	'我們心中的恐懼，永遠比真正的危險巨大的多。',
	'命運掌握在自己手中。要麼你駕馭生命，要麼生命駕馭你，你的心態決定你是坐騎還是騎手。',
	'寧願做過了後悔，也不要錯過了後悔。',
	'不要拿小人的錯誤來懲罰自己，不要在這些微不足道的事情上折磨浪費自己的寶貴時間。',
	'如果我們都去做自己能力做得到的事，我們會讓自己大吃一驚。',
	'出路出路，走出去了，總是會有路的。困難苦難，困在家裡就是難。',
	'學的到東西的事情是鍛鍊，學不到的是磨練。',
	'過錯是暫時的遺憾，而錯過則是永遠的遺憾！',
	'環境不會改變，解決之道在於改變自己。',
	'勇氣是控制恐懼心理，而不是心裡毫無恐懼。',
	'還能衝動，表示你還對生活有激情，總是衝動，表示你還不懂生活。',
	'在實現理想的路途中，必須排除一切干擾，特別是要看清那些美麗的誘惑。',
	'人一生下就會哭，笑是後來才學會的。所以憂傷是一種低級的本能，而快樂是一種更高級的能力。',
	'兩個人共嘗一個痛苦只有半個痛苦，兩個人共享一個歡樂卻有兩個歡樂。',
	'放棄該放棄的是無奈，放棄不該放棄的是無能，不放棄該放棄的是無知，不放棄不該放棄的是執著！',
	'行動是治癒恐懼的良藥，而猶豫、拖延將不斷滋養恐懼。',
	'你把周圍的人看作魔鬼，你就生活在地獄；你把周圍的人看作天使，你就生活在天堂。',
	'人之所以痛苦，在於追求錯誤的東西。',
	'與其說是別人讓你痛苦，不如說自己的修養不夠。',
	'如果你不給自己煩惱，別人也永遠不可能給你煩惱，煩惱都是自己內心製造的。',
	'好好管教自己，不要管別人。',
	'你硬要把單純的事情看得很嚴重，那樣子你會很痛苦。',
	'一杯清水因滴入一滴污水而變污濁，一杯污水卻不會因一滴清水的存在而變清澈。',
	'運氣就是機會碰巧撞到了你的努力。',
	'得之坦然，失之淡然，順其自然，爭其必然。',
	'時間是治療心靈創傷的大師，但絕不是解決問題的高手。',
	'天道酬勤。也許你付出了不一定得到回報，但不付出一定得不到回報。',
	'逆境是成長必經的過程，能勇於接受逆境的人，生命就會日漸的茁壯。',
	'只有不斷找尋機會的人才會及時把握機會。',
	'做一個決定，並不難，難的是付諸行動，並且堅持到底。',
	'如果你能像看別人缺點一樣，如此準確的發現自己的缺點，那麼你的生命將會不平凡。',
	'無論你覺得自己多麼的了不起，也永遠有人比你更強；無論你覺得自己多麼的不幸，永遠有人比你更加不幸。',
	'背負著過去的痛苦，夾雜著現實的煩惱，這對於人的心靈而言是無任何益處。',
	'只有你學會把自己已有的成績都歸零，才能騰出空間去接納更多的新東西，如此才能使自己不斷的超越自己。',
	'人生是一條沒有回程的單行線，上帝不會給你一張返程的票。',
	'對待生活中的每一天若都像生命中的最後一天去對待，人生定會更精彩。',
	'活在昨天的人失去過去，活在明天的人失去未來，活在今天的人擁有過去和未來。',
	'忍別人所不能忍的痛，吃別人所別人所不能吃的苦，是為了收穫得不到的收穫。',
	'大部分人往往對已經失去的機遇捶胸頓足，卻對眼前的機遇熟視無睹。',
	'一個懶惰的少年將來就是一襤褸的老人。',
	'困難是一塊頑石，對於弱者它是絆腳石，對於強者它是墊腳石。',
	'笑對人生，能穿透迷霧；笑對人生，能堅持到底；笑對人生，能化解危機；笑對人生，能照亮黑暗。',
	'人生最大的悲哀不是失去太多，而是計較太多，這也是導致一個人不快樂的重要原因。',
	'我們總是對陌生人太客氣，而對親密的人太苛刻。',
	'人的一生就像一篇文章，只有經過多次精心修改，才能不斷完善。摘自：讀書名言',
	'雖然我們無法改變人生，但可以改變人生觀。雖然我們無法改變環境，但我們可以改變心境。',
	'如果你還認為自己還年輕，還可以蹉跎歲月的話，你終將一事無成，老來嘆息。',
	'當你快樂時，你要想，這快樂不是永恆的。當你痛苦時，你要想，這痛苦也不是永恆的。',
	'命運就像自己的掌紋，雖然彎彎曲曲，卻永遠掌握在自己手中。',
	'不要浪費你的生命，在你一定會後悔的地方上。',
	'激情，這是鼓滿船帆的風。風有時會把船帆吹斷；但沒有風，帆船就不能航行。',
	'人是可以快樂地生活的，只是我們自己選擇了複雜，選擇了嘆息！',
	'不管從什麼時候開始，重要的是開始以後不要停止；不管在什麼時候結束，重要的是結束以後不要後悔。',
	'抱最大的希望，為最大的努力，做最壞的打算。',
	'人生最大的錯誤是不斷擔心會犯錯。',
	'忌妒別人，不會給自己增加任何的好處，忌妒別人，也不可能減少別人的成就。',
	'長得漂亮是優勢，活得漂亮是本事。',
	'大多數人想要改造這個世界，但卻罕有人想改造自己。',
	'每個人都有潛在的能量，只是很容易被習慣所掩蓋，被時間所迷離，被惰性所消磨。',
	'積極的人在每一次憂患中都看到一個機會，而消極的人則在每個機會都看到某種憂患。',
	'創造機會的人是勇者，等待機會的人是愚者。',
	'旁觀者的姓名永遠爬不到比賽的計分板上。',
	'同樣的瓶子，你為什麼要裝毒藥呢？同樣的心理，你為什麼要充滿著煩惱呢？',
	'放棄誰都可以，千萬不要放棄自己！',
	'人生是一場旅行，在乎的不是目的地，是沿途的風景以及看風景的心情。',
	'再長的路，一步步也能走完，再短的路，不邁開雙腳也無法到達。',
	'多一分心力去注意別人，就少一分心力反省自己。',
	'人生就像鐘錶，可以回到起點，卻已不是昨天！',
	'人生就像弈棋，一步失誤，全盤皆輸。',
	'在必要時候需要彎一彎，轉一轉，因為太堅強容易折斷，我們需要更多的柔軟，才能戰勝挫折。',
	'自以為擁有財富的人，其實是被財富所擁有。',
	'人生就像一個動物園，當你以為你在看別人耍猴的時候，卻不知自己也是猴子中的一員！',
	'從絕望中尋找希望，人生終將輝煌。',
	'你不能左右天氣，但可以改變心情。你不能改變容貌，但可以掌握自己。你不能預見明天，但可以珍惜今天。',
	'嘗試去把別人拍過來的磚砌成結實的地基，生活就不會那麼辛苦了。',
	'行動不一定帶來快樂，而無行動則決無快樂。',
	'你可以一無所有，但絕不能一無是處。',
	'突破心理障礙，才能超越自己。',
	'如果我們有著快樂的思想，我們就會快樂；如果我們有著淒慘的思想，我們就會淒慘。',
	'面對困境，悲觀的人因為往往只看到事情消極一面。',
	'不要因為自己還年輕，用健康去換去金錢，等到老了，才明白金錢卻換不來健康。',
	'你不要一直不滿他人，你應該一直檢討自己才對。',
	'心念一轉，萬念皆轉；心路一通，萬路皆通。',
	'愚昧者怨天尤人，無能者長吁短嘆，儒弱者頹然放棄。',
	'智者用無上心智和雙手為自己開闢獨有的天空，搭建生命的舞台。',
	'時間是小偷，他來時悄無聲息，走後損失慘重，機會也是如此。',
	'成功的關鍵在於相信自己有成功的能力。',
	'人的缺點就像花園裡的雜草，如果不及時清理，很快就會佔領整座花園。',
	'滴水穿石不是靠力，而是因為不捨晝夜。',
	'相信自己能力的人，任何事情都能夠做到。',
	'把事情辦好的秘密就是行動。成功之路就是有條理思考之後的行動！行動！行動！',
	'感謝傷害你的人，因為他磨練了你的心志；感謝欺騙你的人，因為他增進了你的智慧；感謝中傷你的人，因為他砥礪了你的人格；感謝鞭打你的人，因為他激發了你的鬥志；感謝遺棄你的人，因為他教導了你該獨立；感謝絆倒你的人，因為他強化了你的能力；感謝斥責你的人，因為他提醒了你的缺點。懷著一顆感恩的心，感激一切使你成長的人！',
	'"Two wrongs don\'t make a right."\nWhen someone has done something bad to you, trying to get revenge will only make things worse.',
	'"The pen is mightier than the sword."\nTrying to convince people with ideas and words is more effective than trying to force people to do what you want.',
	'"When in Rome, do as the Romans."\nAct the way that the people around you are acting. This phrase might come in handy when you\'re traveling abroad notice that people do things differently than you\'re used to.',
	'"The squeaky wheel gets the grease."\nYou can get better service if you complain about something. If you wait patiently, no one\'s going to help you.',
	'"When the going gets tough, the tough get going."\nStrong people don\'t give up when they come across challenges. They just work harder.',
	'"No man is an island."\nYou can\'t live completely independently. Everyone needs help from other people.',
	'"Fortune favors the bold."\nPeople who bravely go after what they want are more successful than people who try to live safely.',
	'"People who live in glass houses should not throw stones."\nDon\'t criticize other people if you\'re not perfect yourself.',
	'"Hope for the best, but prepare for the worst."\nBad things might happen, so be prepared.',
	'"Better late than never."\nIt\'s best to do something on time. But if you can\'t do it on time, do it late.',
	'"Birds of a feather flock together."\nPeople like to spend time with others who are similar to them.',
	'"Keep your friends close and your enemies closer."\nIf you have an enemy, pretend to be friends with them instead of openly fighting with them. That way you can watch them carefully and figure out what they\'re planning.',
	'"A picture is worth a thousand words."\nPictures convey emotions and messages better than written or spoken explanations. That\'s why successful presentations have illustrations.',
	'"There\'s no such thing as a free lunch."\nThings that are offered for free always have a hidden cost.',
	'"There\'s no place like home."\nYour own home is the most comfortable place to be.',
	'"Discretion is the greater part of valor."\nSometimes it\'s important to know when to give up and run away, instead of always acting brave and maybe getting hurt.',
	'"The early bird catches the worm."\nYou should wake up and start work early if you want to succeed.',
	'"Never look a gift horse in the mouth."\nIf someone offers you a gift, don\'t question it.',
	'"You can\'t make an omelet without breaking a few eggs."\nWhen you try to do something great, you\'ll probably make a few people annoyed or angry. Don\'t worry about those people; just focus on the good results.',
	'"God helps those who help themselves."\nDon\'t just wait for good things to happen to you. Work hard to achieve your goals.',
	'"You can\'t always get what you want."\nDon\'t whine and complain if you don\'t get what you wanted.',
	'"Cleanliness is next to godliness."\nBe clean. God likes that.',
	'"A watched pot never boils."\nIf something takes time to finish, don\'t watch it too closely because it will seem like it\'s taking forever.',
	'"Beggars can\'t be choosers."\nIf you\'re asking for a favor from someone else, you have to take whatever they give you.',
	'"Actions speak louder than words."\nJust saying that you\'ll do something doesn\'t mean much. Actually doing it is harder and more meaningful.',
	'"If it ain\'t broke, don\'t fix it."\nDon\'t try to improve something that already works fairly well. You\'ll probably end up causing new problems.',
	'"Practice makes perfect."\nYou have to practice a skill a lot to become good at it.',
	'"Too many cooks spoil the broth."\nWhen there are too many people trying to lead and give their opinions, it\'s confusing and leads to bad results. Jobs and projects should have one or two strong leaders.',
	'"Easy come, easy go."\nWhen you get money quickly, like by winning it, it\'s easy to spend it or lose it quickly as well.',
	'"Don\'t bite the hand that feeds you."\nIf someone\'s paying you or helping you out, you have to be careful not to make them angry or say bad things about them.',
	'"All good things must come to an end."\nYou can\'t keep having good luck or fun forever; eventually it will stop.',
	'"If you can\'t beat \'em, join \'em."\nWhen you try to change someone\'s behavior and it doesn\'t work, you might have to change instead. For example, if you\'re trying to get your classmates to focus on studying but they want to party, maybe you should just party with them.',
	'"One man\'s trash is another man\'s treasure."\nDifferent people have different ideas about what\'s valuable.',
	'"There\'s no time like the present."\nIf you need to do something, don\'t wait until later. Do it now.',
	'"Beauty is in the eye of the beholder."\nDifferent people have different ideas about what\'s beautiful.',
	'"Necessity is the mother of invention."\nWhen you\'re really in need, you think of creative solutions to your problems.',
	'"A penny saved is a penny earned."\nSave your money. Saving money is just like making money.',
	'"Familiarity breeds contempt."\nWhen you\'re around someone for too long, you get tired of them and annoyed by them.',
	'"You can\'t judge a book by its cover."\nThings sometimes look different than they really are. A restaurant that looks old and small might have amazing food, for example.',
	'"Good things come to those who wait."\nBe patient. Eventually something good will happen to you.',
	'"Don\'t put all your eggs in one basket."\nHave a backup plan. Don\'t risk all of your money or time in one plan.',
	'"Two heads are better than one."\nWhen two people cooperate with each other, they come up with better ideas.',
	'"The grass is always greener on the other side of the hill."\nPeople tend to want whatever they don\'t have.',
	'"Do unto others as you would have them do unto you."\nDon\'t do mean things to people.',
	'"A chain is only as strong as its weakest link."\nIf one member of a team doesn\'t perform well, the whole team will fail.',
	'"Honesty is the best policy."\nDon\'t lie.',
	'"Absence makes the heart grow fonder."\nSometimes it\'s good to be away from your partner, because it makes you want to see each other again.',
	'"You can lead a horse to water, but you can\'t make him drink."\nIf you try to help someone, but they don\'t take your advice or offers, give up. You can\'t force someone to accept your help.',
	'"Don\'t count your chickens before they hatch."\nYour plans might not work out, so don\'t start thinking about what you\'ll do after you succeed. Wait until you\'ve already succeeded, and then you can think about what to do next.',
	'"If you want something done right, you have to do it yourself."\nDon\'t trust other people to do important things for you. You have to do things yourself to control the quality of the results.',
)

gLastSaying = 0

def GetSaying():
	global gLastSaying
	n = gLastSaying
	while n == gLastSaying:
		n = random.randint(0, len(SAYINGS) - 1)
	gLastSaying = n
	return SAYINGS[n]


